### ISSUE TITLE
imposible to change the visualVmHome

### ISSUE THREAD

**Issue by pcescipion** [krasa/VisualVMLauncher#13]
Hello,

 when I launched this plugin by the first time there was a pop up asking me for the path  of my viualvm.jar but I cocked it up and I use a wrong path and now I can not change  it. and I am getting all the time the following error 

appId=30447365677748, jdkHome=null, visualVmHome=/usr/lib/jvm/jdk1.7.0_60/lib/visualvm/visualvm/core/locale/core_visualvm.jar: appId=30447365677748, jdkHome=null, visualVmHome=/usr/lib/jvm/jdk1.7.0_60/lib/visualvm/visualvm/core/locale/core_visualvm.jar

Is there any way to change this path for another one  ???

thank you

**Comment by krasa** [comment]
File | Settings | Other Settings | VisualVM Launcher
