### ISSUE TITLE
IntelliJ warning occurs for JDK.

### ISSUE THREAD

**Issue by srhesse** [krasa/VisualVMLauncher#17]
jdkHome=C:\Program Files\RedHat\java-1.8.0-openjdk-1.8.0.111-3, visualVmHome=C:/Toolbox/visualvm_139/bin/visualvm

Works in IntelliJ but reports alert not finding JDK > 1.6. Press Okay.  Press the VisualVM button and it starts.

**Comment by krasa** [comment]
Was probably fixed by #25, you can set the right jdkHome in Settings.
