### ISSUE TITLE
Icons are greyed out on running with Intellij 2017.1

### ISSUE THREAD

**Issue by sourav-dey** [krasa/VisualVMLauncher#18]
On running visual vm plugin on intellij 2017.1, the icons for visualvm are greyed out, but running visual vm manually works fine. It detects my running process and gives me the profiler.
I am using maven as my build configuration system.

**Comment by sourav-dey** [comment]
After playing with it a bit, I found that because maven produces a jar file, so to run it, I have a jar application config and the icons are greyed out in that.
I have my junit tests which creates JUnit application in intellij and the icons are fine.

**Comment by krasa** [comment]
> I have a jar application config

Well, that explains it. Support for that could probably be added. 

btw it seems strange to me to even use it, why not use maven exec plugin or running it directly as  Application config type?
