### ISSUE TITLE
jdkHome=null

### ISSUE THREAD

**Issue by vivekmore** [krasa/VisualVMLauncher#22]
When I try to use the debug with VisualVM in IntelliJ Idea

`Error running 'App': appId=232203515918245, jdkHome=null, visualVmHome=C:/dev/visualvm_141/bin/visualvm.exe`

It has worked till few days back.
Not sure if this has to do with the latest release.

-------
**Environment**

> IntelliJ IDEA 2018.1.5 (Ultimate Edition)
> Build #IU-181.5281.24, built on June 12, 2018
> JRE: 1.8.0_152-release-1136-b39 amd64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Windows 10 10.0

**Comment by krasa** [comment]
Must be something else, only an icon path changed.

**Comment by vivekmore** [comment]
Ok - in that case this can be closed
