### ISSUE TITLE
Possibility to pass arguments for jvisualvm

### ISSUE THREAD

**Issue by TAndronicus** [krasa/VisualVMLauncher#25]
It would be great to be able to pass arguments for jvisualvm for example in case when graal visualvm is used backed by openjdk. `jdkhome` must be set, otherwise visualvm won't start.

Error occurs on linux manjaro, when graal jdk is installed via sdkman.

**Comment by krasa** [comment]
There are cases when jdkhome is currently not passed at all - that could be perhaps fixed by resolving it from the project.

Is your case when you want to pass a different jdkhome than is configured in your project?

**Comment by TAndronicus** [comment]
That's right. I want to use openjdk to run the project, but visualvm itself need jdk from oracle.

**Comment by krasa** [comment]
Try to update

**Comment by krasa** [comment]
And try the Browse button, it has some validatinons, maybe it won't work for openjdk.

**Comment by TAndronicus** [comment]
I don't know if it's me, but most of the times it works like charm, but sometimes it freezes (with same options) and I need to restart intellij / kill the process.

**Comment by krasa** [comment]
When it freezes?

**Comment by TAndronicus** [comment]
VisualVM freezes on splashscreen

**Comment by krasa** [comment]
Then it is VisualVM bug.

**Comment by TAndronicus** [comment]
Alright then, other than that works fine. Thank you very much.

**Comment by krasa** [comment]
No problem.
