### ISSUE TITLE
Please add the high resolution icon for Retina screen on Macbook

### ISSUE THREAD

**Issue by walkingway** [krasa/VisualVMLauncher#26]
Icon looks really sucks on macbook retina screen

**Comment by krasa** [comment]
try this https://github.com/krasa/VisualVMLauncher/releases/download/1.13/VisualVMLauncher.jar

**Comment by krasa** [comment]
i'll make a better circle...

**Comment by krasa** [comment]
https://github.com/krasa/VisualVMLauncher/releases/download/1.13.1/VisualVMLauncher.jar

**Comment by walkingway** [comment]
It's better now

**Comment by tan9** [comment]
In pull request #27, I proposed some vector icons for IntelliJ 2018.2+.

**Comment by tan9** [comment]
@krasa I fount that you moved those svg icons into a sub-folder, this may cause IntelliJ not able to load the vector icon, see: https://github.com/krasa/VisualVMLauncher/commit/e979581f6028ddbf0f14593bb094485fa20b405c#r34027029

**Comment by krasa** [comment]
The idea was to have generated files apart from the rest, but it is just better to use svg directly :-)
It seems that inkscape cannot generate 13x13 svg, so that must be png.

**Comment by krasa** [comment]
I just released it. Thank you @tan9!
