### ISSUE TITLE
Idea on Windows 10 launch visualvm but visualvm crash dirrectly with no message

### ISSUE THREAD

**Issue by kamaloush** [krasa/VisualVMLauncher#34]
Hi,

I successfully installed visualvm an visualvm launcher plugin in Idea.

![Idea launchs VisualVM is broken2](https://user-images.githubusercontent.com/26444823/106029563-82907700-60cd-11eb-8672-36b88a9b751d.gif)

But when I launch visualvm from Idea, it crash directly with no error message:
![Idea launchs VisualVM is broken3](https://user-images.githubusercontent.com/26444823/106029668-99cf6480-60cd-11eb-8deb-9a8e09b08e2c.gif)

Idea is launched as administrator, and visualsm have the compatibility parameter to be launched as administrator. Also, the rights to read the file is open to everybody.

Idea version 
IntelliJ IDEA 2020.3 (Ultimate Edition)
Build #IU-203.5981.155, built on November 30, 2020
Runtime version: 11.0.9+11-b1145.21 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Non-Bundled Plugins: VisualVMLauncher, org.jetbrains.kotlin

Plugin params:
![image](https://user-images.githubusercontent.com/26444823/106029826-c5eae580-60cd-11eb-8f27-29905d83565a.png)

Thanks for your help

**Comment by krasa** [comment]
Try to disable  
![image](https://user-images.githubusercontent.com/1160875/106032221-7c4fca00-60d0-11eb-8ae4-8cd9275d236d.png)

The limitation of the NetBeans platform is that the process dies and the error gets lost, I waqs unable to workaround it so far.

**Comment by kamaloush** [comment]
It works ! Thanks
