### ISSUE TITLE
IntelliJ 2023

### ISSUE THREAD

**Issue by madsvlad2** [krasa/VisualVMLauncher#43]
Will there be an update for IntelliJ 2023?

**Comment by krasa** [comment]
Something not working?

**Comment by madsvlad2** [comment]
The settings page comes up blank and then seems to cause problems with the other setting pages after that.

I manually entered settings in the config XML pointing the plugin to my VisualVM location. After doing that, it does launch VisualVM, but VisualVM is not able to perform any CPU or Memory sampling on the launched application.

I am currently running the community edition IntelliJ 2023.2.

Btw, your plugin has been very convenient and greatly appreciated.

**Comment by krasa** [comment]
>The settings page comes up blank and then seems to cause problems with the other setting pages after that.

Strange, rebuild fixed it, you can update.

>VisualVM is not able to perform any CPU or Memory sampling on the launched application.

That is a matter of used JRE to start VisualVM, it has to match or be compatible with your app.

**Comment by madsvlad2** [comment]
It's working again. Thanks!
