### ISSUE TITLE
VisualVMLauncher (1.23.1-IJ2023.3)  Plugin = NO OPERATION

### ISSUE THREAD

**Issue by rgparis** [krasa/VisualVMLauncher#45]
2023-10-23 Installed plugin VisualVMLauncher (1.23.1-IJ2023.3) from JetBrains Marketplace

### Symptoms: 
On choosing VisualVM using button in IDE "asks" for path to VisualVM executable. Search or the jar and paste or  selection does not recognize jar (to choose) and no operation of VisualVM occurs or attempted by IDE/plugin.
Verified no error messages on plugin install;
Verified IntelliJ sees VisualVM as installed plugin.
Rebooted.
Same results

IntelliJ IDEA 2024.2.4 (Ultimate Edition) Build #IU-242.23726.103, built on October 23, 2024 on 
Windows 11.0 Professional Version 23H2 OS build: 22631.4391
64-bit operating system, x64-based processor Version 23H2 OS build	22631.4391
Processor: Intel(R) Core(TM) i9-14900 2.00 GHz 
Installed RAM: 32.0 GB (31.7 GB usable)
Pen and touch	No pen or touch input is available for this display

**Comment by krasa** [comment]
Select visualvm\bin\visualvm.exe or visualvm/bin/visualvm, not a jar

**Comment by rgparis** [comment]
After install from JetBrains Marketplace:
I have
\JetBrains\IntelliJIdea2024.2\plugins\VisualVMLauncher\
\JetBrains\IntelliJIdea2024.2\plugins\VisualVMLauncher\lib

2024-10-23  10:44    <DIR>          .
2024-10-23  10:44    <DIR>          ..
2024-10-23  10:44           657,952 commons-lang3-3.14.0.jar
2024-10-23  10:44            80,882 instrumented-VisualVMLauncher-1.23.1-IJ2023.3.jar
               2 File(s)        738,834 bytes

No other VisualVM on machine

**Comment by rgparis** [comment]
8-(  more coffee and a bit of reading reveals: USER ERROR.
  Thank you for your patience
